name: Macros Build

# Mengubah trigger dari otomatis (push) menjadi manual
on: 
  workflow_dispatch: 

env:
  # Menghilangkan warning Node.js 20 deprecation
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile macroE (Spam E)
        run: g++ macroE.cpp -o WalkE.exe -static -luser32

      - name: Compile WorkE (Kerja & Survival)
        run: g++ WorkE.cpp -o WorkE.exe -static -luser32

      - name: Simpan Hasil EXE
        uses: actions/upload-artifact@v4
        with:
          name: Macro-Production
          path: |
            WalkE.exe
            WorkE.exe
