name: Ekey Build
on: [push] 

env:
  # Menghilangkan warning Node.js 20 deprecation
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile C++ to EXE
        run: g++ macroE.cpp -o Ekey.exe -static -luser32

      - name: Simpan Hasil EXE
        uses: actions/upload-artifact@v4
        with:
          name: Key-Production
          path: Ekey.exe
